approvedGitRepositories: []

compressionLevel: mixed

enableScripts: false

enableGlobalCache: true

nodeLinker: node-modules

npmMinimalAgeGate: 2d
npmPreapprovedPackages:
  - "@webiny/react-composition"
  - "@webiny/react-properties"
  - "@webiny/utils"
  - "@webiny/wts-client"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
