approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@webiny/react-composition"
  - "@webiny/react-properties"
  - "@webiny/utils"
  - "@webiny/wts-client"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
